services:
  stat:
    container_name: stat
    build:
      context: .
      dockerfile: stat.dockerfile
    ports:
      - 8081:8081
      - 11888:11888
    depends_on:
      - kafka
      - clickhouse
    volumes:
      - ../posts:/posts
    environment:
      KAFKA_BROKER: kafka:9092
      CLICKHOUSE_URL: clickhouse:9000
      TEST_AUTHOR: "test"
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
