openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
paths:
  /register:
    post:
      summary: Register user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User has been registered
        '409':
          description: User with this name already registered
        '400':
          description: Failed to decode json OR There is no username or password field in JSON, or one of them (or both) is empty
        '500':
          description: Some error from postgres
  /update:
    put:
      summary: Обновление данных пользователя
      parameters:
        - name: Cookie
          in: header
          description: auth token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  nullable: true
                lastName:
                  type: string
                  nullable: true
                birthDate:
                  type: string
                  nullable: true
                email:
                  type: string
                  nullable: true
                telephone:
                  type: string
                  nullable: true
      responses:
        '200':
          description: Data was updated
        '400':
          description: Failed to decode json OR User must specify Cookie header
        '403':
          description: Cookie is invalid
        '500':
          description: Some error from postgres
  /login:
    post:
      summary: Auth user with login and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User has been logined successfully
          headers:
            Set-Cookie:
              description: User login token
              schema:
                type: string
        '400':
          description: Failed to decode json OR There is no username or password field in JSON, or one of them (or both) is empty
        '404':
          description: There is no such user or password is wrong
        '500':
          description: Some error from postgres
