/*
 * User Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"database/sql"
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "sw"

	_ "github.com/lib/pq"
)

const (
	dbConnStr = "user=auth password=super_secret_pass dbname=auth_db host=auth_db port=5432 sslmode=disable"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	var err error
	sw.AuthDB, err = sql.Open("postgres", dbConnStr)
	if err != nil {
		log.Fatal(err)
	}

	log.Fatal(http.ListenAndServe(":8080", router))
}
