/*
 * User Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RegisterBody struct {
	Username string `json:"username,omitempty"`

	Password string `json:"password,omitempty"`
}
